### PR TITLE
Get thousands separator from field level, if defined

### PR DESCRIPTION
**Pull request by gperonato**
There is no option at the column level in Pandas. The proposition is to use the separator defined at the field level for all columns.

### CODE REVIEW

**Comment by rgieseke** [comment]
Thanks! Should it only be a field property? I'm not sure i understand the spec right, but it seems to be only defined for a field.

**Comment by gperonato** [comment]
Yes it seems so, I left the previous version at the table schema level for backward compatibility. Anyway, the specs allow extra fields to be added, and the datapackage with the `groupChar` at the schema level is valid.

**Comment by rgieseke** [comment]
If i haven't followed the spec then i think it's better to fix that. Otherwise it will get increasingly hard to maintain pandas-datapackage-reader... would you mind changing that to only support the "correct" way?

**Comment by gperonato** [comment]
In the new commit it's only at the field level.
The remote datapackage should be adapted accordingly though, the test fails
https://raw.githubusercontent.com/rgieseke/pandas-datapackage-reader/master/tests/test-package/datapackage.json

**Comment by rgieseke** [comment]
I guess that's just because it's not merged yet. 

It's a bit tricky, since the Spec allows for column-wise values, but Pandas only global, but i guess we'll keep it that way ...
(Thanks for leaving a comment about that!)
Another option might be to do column-wise conversion but let's hope there is no data with mixed groupChars ....

**Pull request merged**
