### PR TITLE
Support for encoding from datapackage

### PR DESCRIPTION
**Pull request by gperonato**

### CODE REVIEW

**Comment by gperonato** [comment]
Maybe the default encoding should be `utf-8` instead of `None`? https://specs.frictionlessdata.io/data-resource/#recommended-properties.  This would enforce `errors="strict"` in `read_csv()`

**Comment by rgieseke** [comment]
> Maybe the default encoding should be utf-8 instead of None? https://specs.frictionlessdata.io/data-resource/#recommended-properties. This would enforce errors="strict" in read_csv()

Yes, that would make sense!

**Comment by gperonato** [comment]
> > Maybe the default encoding should be utf-8 instead of None? https://specs.frictionlessdata.io/data-resource/#recommended-properties. This would enforce errors="strict" in read_csv()
> 
> Yes, that would make sense!

It is done!

**Comment by rgieseke** [comment]
Awesome! Can you get this to be merge-able again?

**Comment by gperonato** [comment]
It should be already, I rebased the branch

**Comment by rgieseke** [comment]
Nevermind, i merged from the command line (as GitHub didn't let me lazily click the merge button ...)

Thanks again!

**Pull request merged**
